/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iplr.java;

import java.nio.file.Paths;
import java.io.File;
import java.util.Map;
import com.fasterxml.jackson.databind.ObjectMapper;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            ObjectMapper mapper = new ObjectMapper();
            Map<?, ?> map = mapper.readValue(Paths.get("../data/codes.json").toFile(), Map.class);
            for (Map.Entry<?, ?> entry : map.entrySet()) {
                System.out.println(entry.getKey() + "=" + entry.getValue());
            }
        } catch (Exception e) {
            System.out.println("Exception: " + e);
        }
    }
}
