/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iplr.java;

import java.nio.file.Paths;
import java.io.File;
import java.util.Map;
import com.fasterxml.jackson.databind.ObjectMapper;



public class App {
	static League league;

	public static void runLeague() {
		try {
			ObjectMapper mapper = new ObjectMapper();
			CodesJson cj = mapper.readValue(new File("../data/codes.json"), CodesJson.class);
			league = new League(cj);
			league.run();
		} catch (Exception e) {
			System.out.println("Exception: " + e);
		}
	}

	public static void main(String[] args) {
		runLeague();
	}
}
